name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest
    environment: main
    permissions: 
        id-token: write
        contents: read  
        issues: write

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1.5.0
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.0

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Plan Terraform changes
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_org_id: ${{ vars.GCP_ORG_ID }}
          TF_VAR_billing_id: ${{ vars.BILLING_ID }}
          TF_VAR_sql_server_name: ${{ vars.SQL_SERVER_NAME }}
          TF_VAR_sql_admin_username: ${{ vars.SQL_ADMIN_USERNAME }}
          TF_VAR_sql_admin_password: ${{ secrets.SQL_ADMIN_PASSWORD }}
          TF_VAR_gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
          TF_VAR_azure_client_id: ${{ vars.ARM_CLIENT_ID }}
          TF_VAR_azure_subscription_id: ${{ vars.ARM_SUBSCRIPTION_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_azure_tenant_id: ${{ vars.ARM_TENANT_ID }}

      - name: Approve Terraform Plan
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: dppick2solutions

      # Apply Terraform changes (only on push to main)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        env:
            TF_VAR_org_id: ${{ vars.GCP_ORG_ID }}
            TF_VAR_billing_id: ${{ vars.BILLING_ID }}
            TF_VAR_sql_server_name: ${{ vars.SQL_SERVER_NAME }}
            TF_VAR_sql_admin_username: ${{ vars.SQL_ADMIN_USERNAME }}
            TF_VAR_sql_admin_password: ${{ secrets.SQL_ADMIN_PASSWORD }}
            TF_VAR_gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
            TF_VAR_azure_client_id: ${{ vars.ARM_CLIENT_ID }}
            TF_VAR_azure_subscription_id: ${{ vars.ARM_SUBSCRIPTION_ID }}
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
            TF_VAR_azure_tenant_id: ${{ vars.ARM_TENANT_ID }}
  import-csv:
    runs-on: ubuntu-latest
    needs: terraform 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pyodbc pandas

      - name: Import CSV to MSSQL
        env:
          MSSQL_SERVER: ${{ vars.SQL_SERVER_NAME }}.database.windows.net
          MSSQL_DATABASE: BigQueryDemo
          MSSQL_USER: ${{ vars.SQL_ADMIN_USERNAME }}
          MSSQL_PASSWORD: ${{ secrets.SQL_ADMIN_PASSWORD }}
        run: |
          python <<EOF
          import os
          import pandas as pd
          import pyodbc

          # Load CSV
          df = pd.read_csv('sample_data/sample_energy_usage_data.csv')

          # Connect to MSSQL
          conn = pyodbc.connect(
              f"DRIVER={{ODBC Driver 17 for SQL Server}};"
              f"SERVER={os.getenv('MSSQL_SERVER')};"
              f"DATABASE={os.getenv('MSSQL_DATABASE')};"
              f"UID={os.getenv('MSSQL_USER')};"
              f"PWD={os.getenv('MSSQL_PASSWORD')}"
          )
          cursor = conn.cursor()

          # Insert data
          for index, row in df.iterrows():
              cursor.execute("INSERT INTO your_table_name (column1, column2) VALUES (?, ?)", row['column1'], row['column2'])
          conn.commit()
          conn.close()
          EOF